---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m

