---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization-entrypoint
spec:
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: secure-ingress-test
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sources-entrypoint
spec:
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: secure-ingress-test
